image: Visual Studio 2017
platform: Any CPU

environment:
  version: $(APPVEYOR_BUILD_VERSION)-alpha

configuration:
  - Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '%version%'
  package_version: '%version%'
  assembly_version: '%version%'
  file_version: '%version%'
  informational_version: '%version%'
  
before_build:
  - nuget restore
  
build:
  project: Nancy.Swagger.sln

after_test:
  - dotnet pack src/Nancy.Swagger --configuration Release /p:Version=%version%
  - dotnet pack src/Nancy.Swagger.Annotations --configuration Release /p:Version=%version%

artifacts:
  - path: src\Nancy.Swagger\bin\Release\netstandard2.0\Nancy.Swagger.dll
    name: Nancy.Swagger.dll
  - path: src\Nancy.Swagger\bin\Any CPU\Release\Nancy.Swagger.JsonNET.%version%.nupkg
    name: Nancy.Swagger.JsonNET.%version%.nupkg
  - path: src\Nancy.Swagger.Annotations\bin\Release\netstandard2.0\Nancy.Swagger.Annotations.dll
    name: Nancy.Swagger.Annotations.dll
  - path: src\Nancy.Swagger.Annotations\bin\Any CPU\Release\Nancy.Swagger.Annotations.JsonNET.%version%.nupkg
    name: Nancy.Swagger.Annotations.JsonNET.%version%.nupkg
  - path: src\Swagger.ObjectModel\bin\Release\netstandard2.0\Swagger.ObjectModel.dll
    name: Swagger.ObjectModel.dll
  - path: src\Swagger.ObjectModel\bin\Any CPU\Release\Swagger.ObjectModel.JsonNET.%version%.nupkg
    name: Swagger.ObjectModel.JsonNET.%version%.nupkg
    
deploy:
  provider: NuGet
  api_key:
    secure: csyDlyeSjDmdYAQ/PK0GYNZ4ofK/yC6vd5ZLPnG2TgujmrAW7fUiQxjDVOWD4XAX